services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
  frontend:
      build: ./frontend
      ports:
        - "4200:80"
      depends_on:
        - backend
      networks:
        - app-network