# docker-compose.yml
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules 
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=development
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "4200:80" # Exposes frontend (Nginx) on host port 4200
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db 
    restart: unless-stopped
    networks:
      - app-network 

# Define the network used by the services
networks:
  app-network:
    driver: bridge